### PR TITLE
Update CKE to 1.27.2

### PR DESCRIPTION
**Pull request by masa213f**
https://github.com/cybozu-go/neco/issues/2384

- Updates CKE and some depencencies.
- Deletes feature gates that became Beta or GA
  ref: https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/
    - NodeInclusionPolicyInPodTopologySpread is Beta (since 1.26)
    - MinDomainsInPodTopologySpread is Beta (since 1.27)
    - ComponentSLIs is Beta (since 1.27)
    - PodSchedulingReadiness is Beta (since 1.27)
    - PodSchedulingReadiness is Beta (since 1.27)
    - SeccompDefault is GA (since 1.27)

### CODE REVIEW

**Comment by masa213f** [comment]
https://github.com/cybozu-private/neco-apps/actions/runs/7162277440

**Comment by masa213f** [comment]
dctest was passed
https://github.com/cybozu-private/neco-apps/actions/runs/7176782863

**Review by morimoto-cybozu — COMMENTED** [review]
LGTM

**Comment by masa213f** [comment]
rebased and updated cke to 1.27.1

**Comment by masa213f** [comment]
rebased and updated cke to 1.27.2

**Comment by masa213f** [comment]
dctest was passed
https://github.com/cybozu-private/neco-apps/actions/runs/7418936186

**Review by morimoto-cybozu — APPROVED** [review]

**Review by terassyi — APPROVED** [review]
LGTM

**Pull request merged**
