### PR TITLE
Enable Cilium L4LB on prod

### PR DESCRIPTION
**Pull request by ysksuzuki**
Signed-off-by: Yusuke Suzuki <yusuke-suzuki@cybozu.co.jp>

### CODE REVIEW

**Review by zoetrope — COMMENTED** [review]
`cilium-pre.yaml` still remains.
Is it correct?

**Comment by zoetrope** [comment]
`cilium.yaml` and `cilium-pre.yaml` seem to have the same content.

**Comment by ysksuzuki** [comment]
I just left cilium-pre.yaml because we're going to enable XDP only on our staging environment and see if it works stably for a while.

**Review by zoetrope — APPROVED** [review]
LGTM

**Pull request merged**
