### PR TITLE
Update CKE to 1.21.2

### PR DESCRIPTION
**Pull request by morimoto-cybozu**
Signed-off-by: morimoto-cybozu <kenji_morimoto@cybozu.co.jp>

### CODE REVIEW

**Comment by yokaze** [comment]
CKE 1.21.2 is not yet released due to CI error.
https://github.com/cybozu-go/cke/runs/4221748542?check_suite_focus=true

**Comment by morimoto-cybozu** [comment]
@yokaze 
> CKE 1.21.2 is not yet released due to CI error. https://github.com/cybozu-go/cke/runs/4221748542?check_suite_focus=true

Thanks for the notification.  I'll fix it.
Neco CI and release are not affected by the failure of the build of CKE assets because Neco builds CKE binaries from the git repository.
So please make a review of this PR.

**Comment by yokaze** [comment]
@morimoto-cybozu 
I think it's better to release CKE first, because the failing CI may indicate some kind of problem affecting the real cluster.
If there is some kind of proof that the CI failure will not affect the cluster, then it would be OK to go forward.

**Comment by morimoto-cybozu** [comment]
@yokaze 
> If there is some kind of evidence that the CI failure will not affect the cluster, then it would be OK to go forward.

Neco CI confirms that the cluster works well with CKE 1.21.2.

**Comment by morimoto-cybozu** [comment]
I suppose that the cause of the CKE CI failure would be the `flatcar-stable` disk imge used by the CKE sonobuoy test.
The environment of the CKE sonobuoy test is different from that of the Neco CI, as well as from the real environment.

**Review by yokaze — APPROVED** [review]
LGTM

**Pull request merged**
