### PR TITLE
add kubectl-hns to tools

### PR DESCRIPTION
**Pull request by akazs**
since HNC is going to be adopted, added kubectl-hns to cli tools

### CODE REVIEW

**Comment by yokaze** [comment]
I'll take a look

**Review by yokaze — CHANGES_REQUESTED** [review]
Please add license and README files for the linux archive.
```
op-work/
├── DEBIAN
│   └── control
├── VERSION
└── usr
    ├── bin
    │   ├── argocd
    │   ├── kubectl
    │   ├── kubectl-hns
    │   ├── kubectl-moco
    │   ├── kubeseal
    │   ├── kustomize
    │   ├── logcli
    │   ├── stern
    │   └── tsh
    └── share
        └── doc
            ├── argocd
            │   ├── LICENSE
            │   └── README.md
            ├── kubectl
            │   ├── LICENSE
            │   └── README.md
            ├── kubeseal
            │   ├── LICENSE
            │   └── README.md
            ├── kustomize
            │   ├── LICENSE
            │   └── README.md
            ├── logcli
            │   ├── LICENSE
            │   └── README.md
            ├── moco
            │   ├── LICENSE
            │   └── README.md
            ├── stern
            │   ├── LICENSE
            │   └── README.md
            └── teleport
                ├── LICENSE
                └── README.md
```

Is it correct that the Windows version is not provided?

**Comment by akazs** [comment]
> Please add license and README files for the linux archive.

Fixed in the last commit.

> Is it correct that the Windows version is not provided?

Currently upstream does not provide Windows executable.
https://github.com/kubernetes-sigs/hierarchical-namespaces/issues/22
Windows binary will be added if upstream starts providing it in future releases.

**Review by yokaze — APPROVED** [review]
LGTM. Please merge this PR as a single commit:
- merge this PR using squash, or
- unify into a single commit and request review again.

**Pull request merged**
