### PR TITLE
Return to asia-northeast1-c with C2 instance & NVMe local SSD

### PR DESCRIPTION
**Pull request by ymmt2005**

### CODE REVIEW

**Review by toshipp — COMMENTED** [review]
Looks good.
BTW, I don't understand why multiple local-ssd is needed.

I think commit comment "hoge" should be changed...

**Comment by ymmt2005** [comment]
@toshipp 
>  why multiple local-ssd is needed.

C2 instances allows 0, 4, or 8 local SSDs only.

**Comment by toshipp** [comment]
I got it.

Would you revise commit message if other reviewers have no objection?

**Comment by ymmt2005** [comment]
sure.

**Review by ysksuzuki — APPROVED** [review]
LGTM

**Pull request merged**
