### PR TITLE
follow golang 1.17 and updated tools

### PR DESCRIPTION
**Pull request by umezawatakeshi**
Signed-off-by: UMEZAWA Takeshi <takeshi-umezawa@cybozu.co.jp>

### CODE REVIEW

**Review by zoetrope — DISMISSED** [review]
LGTM

**Review by morimoto-cybozu — APPROVED** [review]
LGTM

**Review by ysksuzuki — APPROVED** [review]

**Comment by ysksuzuki** [comment]
Sorry, I'll ignore Coil v2.0.12 on #1762

**Comment by umezawatakeshi** [comment]
rebased

**Review by ysksuzuki — APPROVED** [review]

**Pull request merged**
