### PR TITLE
Remove ingress-watcher

### PR DESCRIPTION
**Pull request by binoue**
We will stop using ingress-watcher, so this PR removes its source code, service, and documtation.
**Do not** merge this PR before making sure that `neco-apps` CI will pass without `ingress-watcher.service`

Signed-off-by: binoue <banji-inoue@cybozu.co.jp>

### CODE REVIEW

**Review by masa213f — CHANGES_REQUESTED** [review]
Please update go.mod. There are minor diff.
```
diff --git a/go.mod b/go.mod
index 15015042..cdc95f6b 100644
--- a/go.mod
+++ b/go.mod
@@ -30,7 +30,7 @@ require (
        github.com/onsi/gomega v1.10.5
        github.com/opencontainers/image-spec v1.0.2-0.20190823105129-775207bd45b6 // indirect
        github.com/pelletier/go-toml v1.3.0 // indirect
-       github.com/prometheus/client_golang v1.9.0
+       github.com/prometheus/client_golang v1.9.0 // indirect
        github.com/prometheus/client_model v0.2.0
        github.com/prometheus/common v0.15.0
        github.com/sirupsen/logrus v1.7.0 // indirect
```

**Review by morimoto-cybozu — COMMENTED** [review]
No other comment.

**Review by masa213f — APPROVED** [review]
LGTM

**Review by morimoto-cybozu — DISMISSED** [review]
LGTM

**Review by morimoto-cybozu — APPROVED** [review]
LGTM

**Pull request merged**
