### PR TITLE
use ghcr.io and update artifacts.go

### PR DESCRIPTION
**Pull request by YZ775**

### CODE REVIEW

**Comment by yokaze** [comment]
@chez-shanpu Could you please confirm that we can update bird immediately?

**Comment by chez-shanpu** [comment]
@yokaze 
> Could you please confirm that we can update bird immediately?

Yes, we can. As far as I checked, there is no breaking changes.

**Comment by YZ775** [comment]
I rebased this branch because https://github.com/cybozu-go/neco/pull/2527 was merged.

**Review by chez-shanpu — APPROVED** [review]
LGTM

**Pull request merged**
